// Generates docs/ASSET_PROMPTS.md and docs/asset_prompts.json from the game's own data,
// so asset names always match what the engine looks for.
//   node tools/make_prompts.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ctx = vm.createContext({ console, Math, Date, JSON });
for (const f of ['util.js', 'data.js']) vm.runInContext(readFileSync(join(root, 'src', f), 'utf8') + '\n', ctx, { filename: f });
const get = expr => vm.runInContext(expr, ctx);
const ENEMIES = get('ENEMIES'), CHARS = get('CHARS');

const STYLE = 'painterly JRPG key art, Belle Époque gothic, deep vermilion, ivory and aged gold palette, dramatic rim light, in the mood of Clair Obscur, Chrono Trigger, Shadow Hearts and .hack';
const looks = {
  vesper: 'a 19-year-old woman, dark plum ponytail, crimson long coat with gold trim, white scarf, rapier, a thin glowing red ring (the Judgment Halo) on her finger',
  gaspard: 'a 27-year-old bearded engineer in a black bowler hat with brass goggles, teal long coat with brass trim, heavy revolver',
  ilse: 'a pale medium with long silver hair, small black hat with a violet feather and veil, black mourning dress with violet trim, black parasol, sorrowful eyes',
  tally: 'a cheerful hacker avatar, spiky cyan hair, glowing cyan visor, dark teal jacket with neon circuit lines, glitch-staff, pixel-glitch artifacts',
  curator: 'a masked figure all in ivory: tall white top hat, blank white mask with red painted eyes, long white robes with vermilion lining, giant paintbrush dripping vermilion',
  oriel: 'an ancient bearded sage in emerald hooded robes with gold trim, kind eyes, white beard',
  aura: 'a small pale child-like AI with long white-blue hair, glowing pale blue eyes, white dress, subtle glitch particles',
};
const bgs = {
  aurelle: 'a Belle Époque city plaza at dusk, gaslamps, a clocktower, a huge vermilion halo ring in the sky, patches of blank white paper where the sky is erased',
  opera: 'an opera house stage, red velvet curtains, gilded proscenium, chandelier, footlights, empty and eerie',
  catacombs: 'ancient catacomb arches receding into darkness, torches, bone piles, green mist',
  woods: 'a twilight enchanted forest, giant dark trunks, shafts of gold light, fireflies, teal mist',
  temple: 'a marble temple hall with verdigris-stained pillars, a huge stained-glass rose window, golden light shafts',
  terminus: 'a synthwave digital city at night, cyan grid floor, magenta sun, floating data cubes',
  datacore: 'a corrupted red-and-black server core, glitch bars, a huge red eye in a ring, magenta static',
  lacuna: 'an endless white paper void with faint pencil sketches, a giant golden picture frame, vermilion ink dripping from above',
};
const rows = [];
const add = (file, kind, prompt, spec) => rows.push({ file: file + '.png', kind, prompt, spec });
for (const [id, t] of Object.entries(looks)) {
  add('portrait_' + id, 'portrait', `Bust portrait of ${t}. Face centred and large, plain dark background, ${STYLE}.`, 'square 1024x1024, face in the upper-middle');
  if (id !== 'oriel') add('battle_' + id, 'battle sprite', `Full-body character of ${t}, side view facing LEFT, dynamic ready stance, flat solid magenta (#ff00ff) background, no shadow, ${STYLE}.`, 'portrait ~768x1024, flat background is auto-removed');
}
for (const [id, t] of Object.entries(bgs)) add('bg_' + id, 'battle backdrop', `Wide battle backdrop: ${t}. Empty foreground floor for characters to stand on, no characters, ${STYLE}.`, '16:9, 1920x1080');
add('title_bg', 'title art', `Title screen art: a vast vermilion halo ring over a silhouetted Belle Époque skyline at dusk, embers, ink drips, ${STYLE}. Leave the upper third clear for a logo.`, '16:9, 1920x1080');
for (const [id, e] of Object.entries(ENEMIES)) {
  add('enemy_' + id, e.boss ? 'boss' : 'enemy', `${e.name}: ${e.desc} Creature/monster design, full body, facing RIGHT, ${e.boss ? 'imposing boss scale, ' : ''}flat solid magenta (#ff00ff) background, no shadow, ${STYLE}.`, 'about 1024px on the long side, flat background auto-removed');
}
mkdirSync(join(root, 'docs'), { recursive: true });
writeFileSync(join(root, 'docs', 'asset_prompts.json'), JSON.stringify(rows, null, 2));
let md = `# Asset prompts (PixVerse / any image generator)\n\nGenerated by \`node tools/make_prompts.mjs\` — do not edit by hand.\n\nThe game is fully playable with its built-in procedural art. Any PNG you drop into \`assets/ai/\` **with the exact filename below** replaces the procedural version. After adding files run \`node tools/make_manifest.mjs\`.\n\n**Tips**\n- Sprites (\`battle_*\`, \`enemy_*\`): ask for a *flat solid magenta background*; the engine removes it automatically (or supply a transparent PNG).\n- Keep one consistent art style across all pieces: reuse the style line at the end of every prompt.\n- Portraits are cropped square (cover); backdrops are cropped to 16:9.\n\n| File | Kind | Spec | Prompt |\n|---|---|---|---|\n`;
for (const r of rows) md += `| \`${r.file}\` | ${r.kind} | ${r.spec} | ${r.prompt.replace(/\|/g, '/')} |\n`;
writeFileSync(join(root, 'docs', 'ASSET_PROMPTS.md'), md);
console.log(`wrote ${rows.length} prompts`);
