// Scans assets/ai/*.png and writes assets/ai/manifest.js so the game loads only files that exist.
// Usage: node tools/make_manifest.mjs
import { readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const dir = join(dirname(fileURLToPath(import.meta.url)), '..', 'assets', 'ai');
const names = readdirSync(dir).filter(f => f.toLowerCase().endsWith('.png')).map(f => f.slice(0, -4)).sort();
const body = `/* Generated by tools/make_manifest.mjs — ${names.length} external asset(s). */\nwindow.VR_ASSETS = ${JSON.stringify(names)};\n`;
writeFileSync(join(dir, 'manifest.js'), body);
console.log(`manifest.js: ${names.length} asset(s)`, names.join(', '));
